version: '3.8'

services:
    frontend:
        image: node:20
        working_dir: /app
        volumes:
            - .:/app
        ports:
            - "3000:3000"
        command: sh -c "npm install && npm start"